name: household_expense_project
description: "Household expense project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  material_symbols_icons: ^4.2719.3
  collection: ^1.16.0
  fl_chart: ^0.70.2

  provider: ^6.0.0        #provider
  go_router: ^14.6.2     #go_router
  
  keyboard_actions: 
    path:  ./custom_package/keyboard_actions-4.2.0 #keyboard_actions

  #localization
  flutter_localizations:
    sdk: flutter
  intl: any

  #sqlite
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.3

  #riverpod
  #flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

  shared_preferences: ^2.3.2
  auto_size_text: ^3.0.0
  holiday_jp: ^0.0.8
  google_mobile_ads: ^5.3.1
  firebase_core: ^3.11.0
  cloud_functions: ^5.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  #riverpod
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.9
  custom_lint: ^0.7.2
  riverpod_lint: ^2.3.10

#admob利用時のvmエラー回避用
dependency_overrides:
  webview_flutter_wkwebview: 3.17.0

flutter:
  generate: true       #多言語対応のファイルが自動生成
  uses-material-design: true

  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: fonts/NotoSans/NotoSansJP-Thin.ttf
          weight: 100
        - asset: fonts/NotoSans/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: fonts/NotoSans/NotoSansJP-Light.ttf
          weight: 300
        - asset: fonts/NotoSans/NotoSansJP-Regular.ttf
          weight: 400
        - asset: fonts/NotoSans/NotoSansJP-Medium.ttf
          weight: 500
        - asset: fonts/NotoSans/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: fonts/NotoSans/NotoSansJP-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: fonts/NotoSans/NotoSansJP-Black.ttf
          weight: 900