import "package:flutter/material.dart";

class MonoMaterialTheme {
  final TextTheme textTheme;

  const MonoMaterialTheme(this.textTheme);

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff1b1b1b),
      surfaceTint: Color(0xff5f5e5e),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff303030),
      onPrimaryContainer: Color(0xff999797),
      secondary: Color(0xff5f5e5e),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffe5e2e1),
      onSecondaryContainer: Color(0xff656464),
      tertiary: Color(0xff5d5c5c),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff767474),
      onTertiaryContainer: Color(0xfffcfcff),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff93000a),
      surface: Color(0xfffdf8f8),
      onSurface: Color(0xff1c1b1b),
      onSurfaceVariant: Color(0xff444748),
      outline: Color(0xff747878),
      outlineVariant: Color(0xffc4c7c7),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffc8c6c6),
      primaryFixed: Color(0xffe4e2e1),
      onPrimaryFixed: Color(0xff1b1c1c),
      primaryFixedDim: Color(0xffc8c6c6),
      onPrimaryFixedVariant: Color(0xff474747),
      secondaryFixed: Color(0xffe5e2e1),
      onSecondaryFixed: Color(0xff1c1b1b),
      secondaryFixedDim: Color(0xffc9c6c5),
      onSecondaryFixedVariant: Color(0xff474646),
      tertiaryFixed: Color(0xffe5e2e1),
      onTertiaryFixed: Color(0xff1c1b1c),
      tertiaryFixedDim: Color(0xffc9c6c6),
      onTertiaryFixedVariant: Color(0xff474647),
      surfaceDim: Color(0xffddd9d8),
      surfaceBright: Color(0xfffdf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff7f3f2),
      surfaceContainer: Color(0xfff1edec),
      surfaceContainerHigh: Color(0xffebe7e7),
      surfaceContainerHighest: Color(0xffe5e2e1),
    );
  }

  ThemeData light() {
    return theme(lightScheme());
  }

  static ColorScheme lightMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff1b1b1b),
      surfaceTint: Color(0xff5f5e5e),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff303030),
      onPrimaryContainer: Color(0xffbfbdbd),
      secondary: Color(0xff373636),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff6e6d6c),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff373636),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff6e6d6d),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff740006),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffcf2c27),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffdf8f8),
      onSurface: Color(0xff111111),
      onSurfaceVariant: Color(0xff333737),
      outline: Color(0xff505354),
      outlineVariant: Color(0xff6a6e6e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffc8c6c6),
      primaryFixed: Color(0xff6e6d6d),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff555554),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff6e6d6c),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff565454),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff6e6d6d),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff555455),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffc9c6c5),
      surfaceBright: Color(0xfffdf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff7f3f2),
      surfaceContainer: Color(0xffebe7e7),
      surfaceContainerHigh: Color(0xffe0dcdb),
      surfaceContainerHighest: Color(0xffd4d1d0),
    );
  }

  ThemeData lightMediumContrast() {
    return theme(lightMediumContrastScheme());
  }

  static ColorScheme lightHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff1b1b1b),
      surfaceTint: Color(0xff5f5e5e),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff303030),
      onPrimaryContainer: Color(0xffeeebea),
      secondary: Color(0xff2c2c2c),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff4a4949),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff2c2c2c),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff4a4949),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff600004),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff98000a),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffdf8f8),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff000000),
      outline: Color(0xff292d2d),
      outlineVariant: Color(0xff464a4a),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffc8c6c6),
      primaryFixed: Color(0xff494949),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff333333),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff4a4949),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff333232),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff4a4949),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff333233),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffbbb8b7),
      surfaceBright: Color(0xfffdf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff4f0ef),
      surfaceContainer: Color(0xffe5e2e1),
      surfaceContainerHigh: Color(0xffd7d4d3),
      surfaceContainerHighest: Color(0xffc9c6c5),
    );
  }

  ThemeData lightHighContrast() {
    return theme(lightHighContrastScheme());
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffc8c6c6),
      surfaceTint: Color(0xffc8c6c6),
      onPrimary: Color(0xff303030),
      primaryContainer: Color(0xff303030),
      onPrimaryContainer: Color(0xff999797),
      secondary: Color(0xffc9c6c5),
      onSecondary: Color(0xff313030),
      secondaryContainer: Color(0xff4a4949),
      onSecondaryContainer: Color(0xffbab8b7),
      tertiary: Color(0xffc9c6c6),
      onTertiary: Color(0xff313030),
      tertiaryContainer: Color(0xff929090),
      onTertiaryContainer: Color(0xff2a292a),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff141313),
      onSurface: Color(0xffe5e2e1),
      onSurfaceVariant: Color(0xffc4c7c7),
      outline: Color(0xff8e9192),
      outlineVariant: Color(0xff444748),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe5e2e1),
      inversePrimary: Color(0xff5f5e5e),
      primaryFixed: Color(0xffe4e2e1),
      onPrimaryFixed: Color(0xff1b1c1c),
      primaryFixedDim: Color(0xffc8c6c6),
      onPrimaryFixedVariant: Color(0xff474747),
      secondaryFixed: Color(0xffe5e2e1),
      onSecondaryFixed: Color(0xff1c1b1b),
      secondaryFixedDim: Color(0xffc9c6c5),
      onSecondaryFixedVariant: Color(0xff474646),
      tertiaryFixed: Color(0xffe5e2e1),
      onTertiaryFixed: Color(0xff1c1b1c),
      tertiaryFixedDim: Color(0xffc9c6c6),
      onTertiaryFixedVariant: Color(0xff474647),
      surfaceDim: Color(0xff141313),
      surfaceBright: Color(0xff3a3939),
      surfaceContainerLowest: Color(0xff0e0e0e),
      surfaceContainerLow: Color(0xff1c1b1b),
      surfaceContainer: Color(0xff201f1f),
      surfaceContainerHigh: Color(0xff2b2a2a),
      surfaceContainerHighest: Color(0xff353434),
    );
  }

  ThemeData dark() {
    return theme(darkScheme());
  }

  static ColorScheme darkMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffdedcdb),
      surfaceTint: Color(0xffc8c6c6),
      onPrimary: Color(0xff252626),
      primaryContainer: Color(0xff929090),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xffdfdcdb),
      onSecondary: Color(0xff262525),
      secondaryContainer: Color(0xff929090),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffdfdcdb),
      onTertiary: Color(0xff262526),
      tertiaryContainer: Color(0xff929090),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xffffd2cc),
      onError: Color(0xff540003),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff141313),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffdadddd),
      outline: Color(0xffafb2b3),
      outlineVariant: Color(0xff8e9191),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe5e2e1),
      inversePrimary: Color(0xff484848),
      primaryFixed: Color(0xffe4e2e1),
      onPrimaryFixed: Color(0xff111111),
      primaryFixedDim: Color(0xffc8c6c6),
      onPrimaryFixedVariant: Color(0xff363636),
      secondaryFixed: Color(0xffe5e2e1),
      onSecondaryFixed: Color(0xff111111),
      secondaryFixedDim: Color(0xffc9c6c5),
      onSecondaryFixedVariant: Color(0xff373636),
      tertiaryFixed: Color(0xffe5e2e1),
      onTertiaryFixed: Color(0xff111111),
      tertiaryFixedDim: Color(0xffc9c6c6),
      onTertiaryFixedVariant: Color(0xff373636),
      surfaceDim: Color(0xff141313),
      surfaceBright: Color(0xff454444),
      surfaceContainerLowest: Color(0xff070707),
      surfaceContainerLow: Color(0xff1e1d1d),
      surfaceContainer: Color(0xff282827),
      surfaceContainerHigh: Color(0xff333232),
      surfaceContainerHighest: Color(0xff3e3d3d),
    );
  }

  ThemeData darkMediumContrast() {
    return theme(darkMediumContrastScheme());
  }

  static ColorScheme darkHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xfff2efef),
      surfaceTint: Color(0xffc8c6c6),
      onPrimary: Color(0xff000000),
      primaryContainer: Color(0xffc4c2c2),
      onPrimaryContainer: Color(0xff0b0b0b),
      secondary: Color(0xfff3efee),
      onSecondary: Color(0xff000000),
      secondaryContainer: Color(0xffc5c2c1),
      onSecondaryContainer: Color(0xff0b0b0b),
      tertiary: Color(0xfff3efef),
      onTertiary: Color(0xff000000),
      tertiaryContainer: Color(0xffc5c2c2),
      onTertiaryContainer: Color(0xff0b0b0b),
      error: Color(0xffffece9),
      onError: Color(0xff000000),
      errorContainer: Color(0xffffaea4),
      onErrorContainer: Color(0xff220001),
      surface: Color(0xff141313),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffffffff),
      outline: Color(0xffeef0f1),
      outlineVariant: Color(0xffc0c3c3),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe5e2e1),
      inversePrimary: Color(0xff484848),
      primaryFixed: Color(0xffe4e2e1),
      onPrimaryFixed: Color(0xff000000),
      primaryFixedDim: Color(0xffc8c6c6),
      onPrimaryFixedVariant: Color(0xff111111),
      secondaryFixed: Color(0xffe5e2e1),
      onSecondaryFixed: Color(0xff000000),
      secondaryFixedDim: Color(0xffc9c6c5),
      onSecondaryFixedVariant: Color(0xff111111),
      tertiaryFixed: Color(0xffe5e2e1),
      onTertiaryFixed: Color(0xff000000),
      tertiaryFixedDim: Color(0xffc9c6c6),
      onTertiaryFixedVariant: Color(0xff111111),
      surfaceDim: Color(0xff141313),
      surfaceBright: Color(0xff51504f),
      surfaceContainerLowest: Color(0xff000000),
      surfaceContainerLow: Color(0xff201f1f),
      surfaceContainer: Color(0xff313030),
      surfaceContainerHigh: Color(0xff3c3b3b),
      surfaceContainerHighest: Color(0xff484646),
    );
  }

  ThemeData darkHighContrast() {
    return theme(darkHighContrastScheme());
  }

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
        colorScheme: colorScheme,
        textTheme: textTheme,
      );
}
